### PR TITLE
Feat/campaign wizard ux and offer card fixes

### LINKED ISSUE #537: Shows Budget as zero and check all other fields in before and after campaign creation, mandatory field should be well indicated ,  for users to know and all data should be well shown and displayed

### LINKED ISSUE #538: Campaign creation and other form filling in the application should disable the proceed button untill all mandatory fields are filled

### PR DESCRIPTION
**Pull request by lele-maxwell**
closes #537
closes #538 

---

**PR Description:**

## Overview
This PR improves the campaign creation experience in the brand dashboard across two areas: the wizard step UX and the accuracy of data displayed on campaign offer cards.

## Campaign Wizard — Step 1 & Step 2 UX

**Problem:** Validation errors were shown as a generic red toast in the bottom corner, giving no indication of which field was wrong. Users had no visual feedback on invalid fields and had to hunt for the issue.

**Changes:**
- Replaced the destructive red toast with an animated amber banner at the top of the form that names the specific issue and shakes to draw attention
- Invalid fields are highlighted with an amber border and background, with an inline error message directly below each field
- Errors clear automatically as the user corrects each field
- On submit, the page auto-scrolls and focuses the first invalid field
- Required fields are clearly marked with `*`
- Applied the same pattern to Step 2 (Campaign Brief) for all 6 required fields: total deliverables, campaign duration, launch date, collaborator payout, offer amount, and submission deadline

**Back navigation fix:**
- During new campaign creation, the Back button on Step 2 correctly returns to Step 1
- When adding a collaborator to an existing campaign, the Back button is hidden — no going back to Step 1 since the campaign already exists

## Campaign Offer Card — Data Accuracy

**Problem:** The "My Offers" card was showing **$0 budget**, **no start date**, and **no due date** despite the user having entered all of this in Step 1.

**Root cause:** Three stacked bugs — budget was hardcoded to `0`, due date was calculated but never stored on the offer object, and `start_date`/`budget_range` were never propagated to the grouped campaign object used by the card renderer.

**Changes:**
- Budget now displays the full range from Step 1: `$min – $max`
- Start date and due date (calculated as `start_date + duration_days`) are now correctly shown
- Removed Assets and Last Update rows — card only shows Step 1 fields: budget range, start date, due date
- All card data sourced exclusively from Step 1 fields (`budget_range`, `start_date`, `duration_days`)

### CODE REVIEW

File: likelee-ui/src/pages/BrandCampaignDashboard.tsx [hunk 1]
```diff
@@ -298,6 +308,7 @@ export default function BrandCampaignDashboard({
       const brandCampaignId = String(context?.brandCampaignId || "").trim();
 
       setBrandCampaignId(brandCampaignId);
+      setIsExistingCampaign(true);
```
Comment (Christiantyemele) [inline likelee-ui/src/pages/BrandCampaignDashboard.tsx:311]: This new `isExistingCampaign` branch makes the embedded flow depend on whether a previous open carried a `brandCampaignId`. The problem is the opposite branch still only does `setNewCampaignStep(1)`, so if the user opens an existing campaign first and then opens a brand-new one, the old `brandCampaignId`/form state survives and `ensureCampaignDraft()` can update the previous campaign instead of creating a fresh draft. Please fully reset the wizard state in the `else` path before showing the modal.

File: likelee-ui/src/pages/BrandCampaignDashboard.tsx [hunk 2]
```diff
@@ -1433,6 +1454,7 @@ export default function BrandCampaignDashboard({
     setAwaitingBrandSignature(false);
     setNewCampaignStep(1);
     setBrandCampaignId("");
+    setIsExistingCampaign(false);
```
Comment (Christiantyemele) [inline likelee-ui/src/pages/BrandCampaignDashboard.tsx:1529]: Good call resetting `isExistingCampaign` here, but the new validation state is still left behind. `resetCampaignBuilder()` should also clear `step1FieldErrors`, `step2FieldErrors`, and `wizardErrorBanner`; otherwise canceling a failed attempt and reopening the modal can show stale amber errors from the previous session.

**Review by Christiantyemele — CHANGES_REQUESTED** [review]
Thanks for pushing this through. I found two behavioral regressions worth fixing before merge.

File: likelee-ui/src/pages/BrandCampaignDashboard.tsx [hunk 3]
```diff
@@ -340,7 +351,64 @@ export default function BrandCampaignDashboard({
 
       setNewCampaignStep(safeStep);
     } else {
+      // Full reset for a brand-new campaign — clear any state left from a previous session
```
Comment (Christiantyemele) [inline likelee-ui/src/pages/BrandCampaignDashboard.tsx]: This is now clearing the step-1/step-2 state, but it still does not mirror the full `resetCampaignBuilder()` reset below. In particular it leaves later-step state like `selectedCreatorsById`, `selectedTalentCreatorIds`, `offerByCreatorId`, `contractDraft`, `marketplaceCreators`, and `creatorSearch` intact. That means if someone opens an existing/new campaign, reaches creator selection or contract upload, then reopens a brand-new embedded campaign, step 3/5 can still show stale creator selections or contract/template state from the previous session. Please reuse the full reset logic here (or extract a shared helper) instead of resetting only part of the wizard state.

**Review by Christiantyemele — CHANGES_REQUESTED** [review]
The two previously reported regressions look fixed. I found one follow-up issue in the new reset path that still needs attention.

**Review by Christiantyemele — APPROVED** [review]
